### ISSUE TITLE
Quick copy footprint to clipboard

### ISSUE THREAD

**Issue by dzid26** [markusdd/EasyEDA_to_KiCAD_Lib_UI#1]
Can you add option to quickly copy footprint to the clipboard (3d model ~~can~~ will be downloaded to a temp folder).  Analogous to  what I did here: 
https://github.com/Springer-Electronics/JLC2KiCad_lib/blob/d584306c46d5a42945286c34f9a15b3dc80f7ada/JLC2KiCad_plugin.py#L222-L224
This is best feature of my plugin and I use it all the time to check a fit of components.

**Comment by markusdd** [comment]
This should be possible, but I do not quite get it. What do you do with the footprint text in the clipboard? And how is this linked to the 3d model which is a seperate file?

can you explain a little more?

**Comment by dzid26** [comment]
> This should be possible, but I do not quite get it. What do you do with the footprint text in the clipboard? 

Then you can paste it straight into PCB Editor. 
Clipboard implementaion in Kicad simply uses text to convey the copied footprints (or symbol).  The format is exactly the same as in .kicad_mod file.  So instead of saving footptint to library, you can save it to a temporary location and load it as text to clipboard. The user can simply Ctrl-V in Kicad.

**Comment by markusdd** [comment]
ah ok lol. I did not even know that.

but then would'nt it make more sense to not even download the 3d model in the first place? This can be supressed using `-model` switch without any arguments.

Do I interpret it correctly that you have forked the original python lib to extend it? 
So that would mean shifting this functionality into the UI application.

Have you talked to the original developer if he wants this function upstream so I could call it programmatically?

**Comment by dzid26** [comment]
> Do I interpret it correctly that you have forked the original python lib to extend it? So that would mean shifting this functionality into the UI application.

I  forked it only to add very simple Kicad [GUI ](https://github.com/TousstNicolas/JLC2KiCad_lib/issues/58)in Kicad for downloading the files to a hardcoded path or to a temp folder and copying to clipboard.

> Have you talked to the original developer if he wants this function upstream so I could call it programmatically?

His library only download models to specific location. That seems reasonable. I think we don't need more. 

> but then wouldn't it make more sense to not even download the 3d model in the first place? This can be supressed using `-model` switch without any arguments.

Having 3D models is good to for trying the fitment.   The JLC2KiCad_lib will handle the 3d model path linking automatically if you give it a system temp folder:
<img width="926" alt="image" src="https://github.com/markusdd/EasyEDA_to_KiCAD_Lib_UI/assets/841061/d171fb39-79cb-4428-990a-1045caf79d87">
This is fine ^.

**Comment by markusdd** [comment]
ah ok.

So that would mean adding basically a second set of footrpint settings for temp locations and a button that runs with `-no_symbol` and at the end of the run you would have the footprint in the clipboard.

**Comment by dzid26** [comment]
Yes.  
Python had a module to create new unique temp folder in OS temp directory. Rust might have similar.  - Of course, you can always give more freedom to specify temp folder in the settings if you don't mind extra work :)

Yes, extra button could be like this:
<img width="483" alt="image" src="https://github.com/markusdd/EasyEDA_to_KiCAD_Lib_UI/assets/841061/6b145032-0303-46ed-b040-99a7f1d04f5f">

^ This would be great addition.

**Comment by markusdd** [comment]
Ok, I see, I guess that makes sense.

Let me finish the datasheet download first in the coming days and figure out a release pipeline that builds for all OS'ses, onec I have that I will put htis feature in.

And yes of course rust will have a OS-dependent tmp functionality, that should be easy to do.

**Comment by markusdd** [comment]
Hi, can you check this release please if it works as intended? I tried it and for me it worked great!
https://github.com/markusdd/EasyEDA_to_KiCAD_Lib_UI/releases/tag/v1.0.0

**Comment by dzid26** [comment]
Perfect. This is exactly what I envisioned.  Very useful for quick fitment check.

**Comment by markusdd** [comment]
yup, indeed cool feature, didn't know that worked in KiCAD
