### ISSUE TITLE
Datasheet download fails

### ISSUE THREAD

**Issue by jj-uk** [markusdd/EasyEDA_to_KiCAD_Lib_UI#2]
Downloading of datasheets doesn't seem to work. When opening the PDF in a text editor, it looks like the contents are a webpage copy, not a PDF.

**Comment by markusdd** [comment]
Please share the contents you see and the part url or number you used

**Comment by jj-uk** [comment]
Part # C473012, but all parts I've tried have the same issue.  Generated (downloaded) PDF attached (open in a text editor).

[2304140030_Espressif-Systems-ESP32-WROOM-32D-N4_C473012.pdf](https://github.com/markusdd/EasyEDA_to_KiCAD_Lib_UI/files/14788790/2304140030_Espressif-Systems-ESP32-WROOM-32D-N4_C473012.pdf)

**Comment by markusdd** [comment]
that is extremely odd. will look into that as soon as possible, this looks a bit as if something has changed on their end.

**Comment by markusdd** [comment]
ok, found the problem.

the JSON URL now points to a split screen page with parts info on right and the PDF to the left.
I need to patch this URL in order for the PDF to be downloaded.

The release pipeline for 1.3.0 is currently running. Once that is available, can you please test?

**Comment by markusdd** [comment]
Release is now available: https://github.com/markusdd/EasyEDA_to_KiCAD_Lib_UI/releases/tag/v1.3.0

Please provide feedback and close when fixed. (FYI: you might need to delete the broken PDFs first, it will not override them as I've noticed, but that's a fix for a later day^^)

**Comment by sinalco92** [comment]
Datasheets will be download in the library folder. But in the KiCad Symbol Properties there is a Random Online Link (only for C5441281) to a different datasheets not the download in the library folder. Is its possible to link to the local folder or directly to the data sheet link that are in your link (https://www.lcsc.com/datasheet/). In the symbol library there is from https://item.szlcsc.com/ and everything is on china (I test with V1.3).

**Comment by jj-uk** [comment]
#C473012

Thanks for the update. Datasheets are now being downloaded into the downloads folder.

However, @sinalco92 points out another bug:

In the *.kicad_sym file, property "Datasheet" is incorrect link, e.g.

`(property "Datasheet" "https://item.szlcsc.com/549848.html" (id 3) (at -2.286 0.127 0)`

[default_lib.zip](https://github.com/markusdd/EasyEDA_to_KiCAD_Lib_UI/files/14803699/default_lib.zip)

**Comment by markusdd** [comment]
Hi, this bug needs to be raised seperately at JLC2KiCAD lib, which this project is built on.
I do not interfere with the generation of the symbol files, so please raise an issue over there.

**Comment by jj-uk** [comment]
@sinalco92 I've opened an issue for this over on the TousstNicolas/JLC2KiCad_lib repo:

https://github.com/TousstNicolas/JLC2KiCad_lib/issues/70
