### ISSUE TITLE
Macos Releases are missing an extension

### ISSUE THREAD

**Issue by besi** [markusdd/EasyEDA_to_KiCAD_Lib_UI#4]
Hello there. I did download your program but the file I downloaded is called: `EasyEDA_to_KiCAD_Lib_UI-x86_64-apple-darwin` without a file extension.

I tried `dmg` and `zip` but none of them worked.

**Comment by markusdd** [comment]
it is simply an executable. no extension needed.
this is not a package.

**Comment by besi** [comment]
Thanks for the heads up
