### ISSUE TITLE
Feature discussion: self-updating library of all uncommon LCSC parts 

### ISSUE THREAD

**Issue by riacob** [markusdd/EasyEDA_to_KiCAD_Lib_UI#6]
Perhaps, once per month, the following automation could occur:
1. Server makes a request to LCSC though their API to scrape all the components off of their database, 
2. Server processes each component discarding the common symbols and footprints (eg. resistor, caps, inductors; 0805, 1206)
3. Server generates symbols, footprints, 3d models
4. Server pushes all the data to a public github repo*,**

*The repo can have two forks:
- Raw, containing all the data scraped and processed
- Reviewed, where symbol and footprint are checked and approved by volounteers 
**Repo is incremental, meaning that the only way to remove or modify components is through pull requests

Notes: 
- This could very well be repeated for each distributor, avoiding the same mfr part# if it is already available in the database
- Objects without images or package references should perhaps be avoided, as it is more likely to produce wrong results

Any suggestions on where else I could post this idea and find people who are interested in its development?

**Comment by markusdd** [comment]
I am sorry to tell you this so bluntly but what you want to do there is illegal^^

**Comment by riacob** [comment]
You mean the scraping? I think something could be arranged directly with LCSC.

**Comment by markusdd** [comment]
the scraping is already problemtic as such, and they will not concur with that.

The part that is flat-out illegal is hosting the EasyEDA symbols and 3d-models somewhere else.
All this content belongs to LCSC and potential upstream vendors. You cannot just scrape all that and host it somewhere else.

**Comment by riacob** [comment]
Technically it's stealing only if it is a 1-1 copy..
But yes, I agree that this is a complicated matter.
Kind of a shame honestly, like everything else IP rights related...

**Comment by markusdd** [comment]
yup.

But with that I guess we can close here, although it is kind of unsatisfying ;)
